moshell-lang/moshell

lexer/src/token.rs
parser/src/aspects.rs
parser/src/aspects/base_parser.rs
parser/src/aspects/call_parser.rs
parser/src/aspects/literal_parser.rs
parser/src/aspects/var_declaration_parser.rs
parser/src/aspects/var_reference_parser.rs
parser/src/ast.rs
parser/src/ast/variable.rs
parser/src/parser.rs
parser/tests/expr.rs
parser/tests/with_lexer.rs

This PR adds support for template strings and variable references in different places:
```kt
// Template strings
val prefix = 'my-'
val cmd = 'ssh'
"$prefix$cmd" root@vm // Now correctly expand to `my-ssh root@vm`
```
```kt
// Standard arguments
val count = 1
grep p$count // Now correctly expand to `grep p1`
```
```kt
// Variable names can be delimited with curly brackets
val verb = 'is '
val ready = 'ready'
echo "${verb}${ready}!" // Now correctly expand to `echo is ready!`
```
Variable references are not interpreted in literals with simple quotes:
```kt
val n = 10
grep '$n' // Expand as usual to `grep $n`
```
Fix #6

Support variable references and arbitrary arguments

---

parser/src/aspects/block_parser.rs
parser/src/aspects/call_parser.rs
parser/src/aspects/literal_parser.rs
parser/src/aspects/var_declaration_parser.rs
parser/src/ast/literal.rs
parser/src/lib.rs
parser/src/source.rs
parser/tests/expr.rs
parser/tests/with_lexer.rs

Some tests that don't use the lexer have been shortened since strings in those tests are not guaranteed to be adjacent in memory.
Fix #17

Use the raw lexme in string literals

---

lexer/src/token.rs
parser/src/aspects.rs
parser/src/aspects/call_parser.rs
parser/src/aspects/literal_parser.rs
parser/src/aspects/substitution_parser.rs
parser/src/aspects/var_reference_parser.rs
parser/src/moves.rs
parser/src/parser.rs
parser/tests/with_lexer.rs

This PR adds support for parsing command substitution.
A substitution is a way to start a new statement in the middle of another.
Command capture:
```kt
val current = $(pwd)
```
Command evaluation:
```kt
val shifted = @(shift)
```
Arithmetic evaluation would wait for #19.
Fix #16

Parse command substitution

---

parser/src/aspects.rs
parser/src/aspects/binary_operation.rs
parser/src/aspects/call.rs
parser/src/aspects/group.rs
parser/src/aspects/literal.rs
parser/src/aspects/redirection.rs
parser/src/aspects/substitution.rs
parser/src/aspects/var_declaration.rs
parser/src/aspects/var_reference.rs
parser/src/ast/variable.rs
parser/src/parser.rs
parser/tests/expr.rs
parser/tests/with_lexer.rs

- The `_aspect` suffix is redundant for files as they already are in the `/aspects`.
- There was a little misleading naming convention for parser aspects, as they were named `<name>Parser` instead of `<name>Aspect`.
- Reduced `VarReference` and `TypedVariable` size by changing type of `name` fields by actual name str slice instead of a token, which also removes some useless checks for further steps

Proposal to reduce names in /aspects folder, rename XParser traits to XAspect, and replace 'name' token fields with str

---

cli/Cargo.toml
cli/src/cli.rs
cli/src/main.rs
cli/src/repl.rs
cli/src/report.rs
lexer/src/token.rs
parser/src/aspects/binary_operation.rs
parser/src/aspects/call.rs
parser/src/aspects/expr_list.rs
parser/src/aspects/function_declaration.rs
parser/src/aspects/group.rs
parser/src/aspects/literal.rs
parser/src/aspects/match.rs
parser/src/aspects/modules.rs
parser/src/aspects/type.rs
parser/src/aspects/var_declaration.rs
parser/src/aspects/var_reference.rs
parser/src/moves.rs
parser/src/parser.rs
parser/tests/err.rs
parser/tests/expr.rs

Error messages are an important part of Moshell, so this PR goes further by allowing more than one error in a single expression. Some work has been done here to have a smart repositioning to ensure that an error causes the least false positives after. Fix #46 
Repositioning strategy
----------------------
Cursor repositioning depends on two factors :
- The error kind that occurs. If it is a mismatched delimiter error, always advances to the next valid closing delimiter. This is a punctuation error, so it is expected that it could easily go to the end of the file.
- The parser's context. There may sometimes have only one error per line, but if there are clearly defined delimiters like parenthesis or commas, there is no need to go that far.
Repositioning heavily depends on the group which …

Support local parser errors

---

parser/src/aspects/redirection.rs
parser/src/parser.rs
parser/tests/with_lexer.rs

Removes the bar character from the non-infix operator list, and use a more generic parser when looking for the next parts of a pipeline.
Fix #95

Allow any expression in a pipeline

---

lexer/src/token.rs
parser/src/aspects/call.rs
parser/src/aspects/lambda_def.rs
parser/src/aspects/substitution.rs
parser/src/aspects/var_declaration.rs
parser/src/aspects/var_reference.rs
parser/src/cursor.rs
parser/src/moves.rs
parser/src/parser.rs
parser/tests/err.rs
parser/tests/with_lexer.rs

The original goal was to fix #98, by allowing only one token after the `$` sign in a variable reference. Updating this parser revealed that the square brackets were not properly popped from the delimiter stack if an error occurred.
#100 could originally use the parser directly, but it was encountered that variable declarations without an initializer would actually consume the *end of expression* token, disallowing any subsequent expressions.
Another found corner case is that `val variable cast Array` indicates the error on the whitespace between `cast` and `Array`, while `{ val variable cast Array }` indicates the error on `cast`. The root cause is that the "expected end of expression" message is handled differently in a block. More specifically, the group parser does not use a `force()` …

Fix cursor usages around variable parsing

---

lexer/src/lexer.rs
lexer/src/token.rs
lexer/tests/sample.rs
parser/src/aspects/binary_operation.rs
parser/src/aspects/call.rs
parser/src/aspects/expr_list.rs
parser/src/aspects/function_declaration.rs
parser/src/aspects/group.rs
parser/src/aspects/loop.rs
parser/src/aspects/match.rs
parser/src/aspects/substitution.rs
parser/src/moves.rs
parser/src/parser.rs

These obscure move is used in multiple places in the code base:
- `eox()` determines the end of an expression, but only with new lines.
- `eox().or(eod())` determines the end of an expression, more precisely, since a closing delimiter most likely also means the end of an expression.
- `not(blanks().then(eox().or(eod())))`, like `eox()` but allow intermediate new lines.
Those compositions hint that something is not handled properly.
Consider a return (https://github.com/moshell-lang/moshell/blob/master/parser/src/aspects/function_declaration.rs#L64):
If the line ends, or if the enclosing group ends, it's a void return. This intent is actually the end of an expression, which is not fully covered by simply `eox()`. This PR tackles that by merging the `eox()` move with the idea behind `eod()` …

Redefine end of expressions

---

analyzer/src/diagnostic.rs
analyzer/src/engine.rs
analyzer/src/environment.rs
analyzer/src/environment/variables.rs
analyzer/src/imports.rs
analyzer/src/relations.rs
analyzer/src/steps/collect.rs
analyzer/src/steps/resolve.rs
analyzer/src/steps/resolve/diagnostics.rs
analyzer/src/steps/resolve/import.rs
analyzer/src/steps/resolve/symbol.rs
analyzer/src/steps/shared_diagnostics.rs
analyzer/src/steps/typing.rs
analyzer/src/types/ctx.rs
analyzer/src/types/engine.rs
analyzer/src/types/hir.rs
analyzer/src/types/ty.rs
analyzer/tests/collect_debug.rs

This simple pull request refactors some structure names in order to be less misleading and more straightforward 
- `GlobalObjectId` => `RelationId` as they ARE relations identifier
- `SourceObjectId` => `SourceId`
- Created `LocalId` in order to pair with `RelationId`
- `Symbol::Global` => `Symbol::External` as "global" symbols are more of global variables, functions, defined in script's roots. This refactor better matches with the fact that a symbol can either be local to environment (thus `Symbol::Local`) or external (thus `Symbol::External`).
- `Object` => `Relation` as its identifier is `RelationId` that could be flustered with `ObjectId`.
- `Relations::objects` => `Relations::relations` to match `Object` => `Relation` refactor
The relations' map were unexposed, and `Relations` now …

Analyzer refactors, encapsulate `Relations`

---

analyzer/src/steps/typing.rs
compiler/src/bytecode.rs
compiler/src/emit.rs
compiler/src/emit/invoke.rs
compiler/src/emit/jump.rs
compiler/src/emit/native.rs

This pull request, as discussed in #112, adds a new state during compilation phase (`EmissionState::use_values`) which helps the compiler tracking unused values pushed from expressions.
Those check are needed to keep an operand stack as small as possible and with a deterministic size

Pop unused expression values

---

analyzer/src/diagnostic.rs
analyzer/src/engine.rs
analyzer/src/importer.rs
analyzer/src/steps/collect.rs
analyzer/src/steps/resolve.rs
analyzer/src/steps/resolve/diagnostics.rs
analyzer/src/steps/shared_diagnostics.rs
analyzer/src/steps/typing.rs
analyzer/src/steps/typing/coercion.rs
analyzer/src/steps/typing/exploration.rs
analyzer/src/steps/typing/function.rs
analyzer/src/steps/typing/lower.rs
analyzer/src/types/ty.rs
cli/build.rs
cli/src/cli.rs
cli/src/main.rs
cli/src/pipeline.rs
cli/src/repl.rs
cli/src/report.rs
context/src/source.rs

The analyzer has the ability to import multiple sources, but was not implemented for real files.
Importing files
===============
This PR distinguishes three possible outputs if fetching a source from a `Name` fails:
- The source doesn't exist, but a parent may exist. In this case, return `Ok(None)`, to continue trying importing a similar `Name`.
- The source do exist, but is not usable. This might be due to file permissions or to a parsing error. In that case, return `Err(ImportError)` to stop the resolution here.
- The source is intelligible, return `Ok(Some(_))`.
The command line interface is now able to read files and display parse errors that could errors. This can be done either using the `-s <file>` option or in the REPL (still not able to remember previously executed lines).
A file …

Import multiple files

---

analyzer/src/engine.rs
analyzer/src/steps/collect.rs
analyzer/src/steps/resolve.rs

the commit https://github.com/moshell-lang/moshell/commit/b37a0f5216e1ed9eabb4f809cc904da6e359cf7c did an undesirable regression which made capture resolution through non-direct parents not working.
This pull request fixes this issue by making the collector instantly attach created environments in the engine, and then work with environments inside the engine.

Fix symbol capture in collection phase

---

Cargo.toml
cli/Cargo.toml
cli/lang_tests/flow/break_loop.msh
cli/lang_tests/flow/function_call.msh
cli/lang_tests/redir/file_redirection.msh
cli/lang_tests/redir/pipeline_exit.msh
cli/lang_tests/redir/pipeline_text.msh
cli/lang_tests/redir/silent_sigpipe.msh
cli/lang_tests/run.rs
cli/src/cli.rs
vm/Cargo.toml
vm/benches/exec_benchmark.rs
vm/binding/lib.rs
vm/build.rs

The VM is mostly tested manually or with primitive scripts. It's time to have a proper testing environment that directly targets the CLI binary.
This will allow playing with multiple files to testing the file importer in real conditions. For now, a few tests have been written with the [*lang_tester*](https://github.com/softdevteam/lang_tester/) crate that checks the execution output.
This PR also pull Criterion to benchmark the virtual machine performance. It has been added to a `vm` crate, that now contain the FFI code instead of the `cli` crate. The benchmarks belong to the crate directly, so compiling with the `test` profile will compile Criterion despite not being used. Benchmarks profile variable accesses and function calls.

Automatically test the VM implementation

---

analyzer/src/steps/collect.rs
ast/src/call.rs
parser/src/aspects/binary_operation.rs
parser/src/aspects/call.rs
parser/src/aspects/detached.rs
parser/src/aspects/function_declaration.rs
parser/src/aspects/group.rs
parser/src/aspects/if_else.rs
parser/src/aspects/lambda_def.rs
parser/src/aspects/loop.rs
parser/src/aspects/match.rs
parser/src/aspects/redirection.rs
parser/src/aspects/substitution.rs
parser/src/aspects/test.rs
parser/src/aspects/type.rs
parser/src/aspects/var_declaration.rs
parser/tests/err.rs
parser/tests/expr.rs
parser/tests/with_lexer.rs

This pull request removes from the AST the inclusion `path` and `type_parameters` fields.
As we discussed that moshell functions and system command calls cannot get mixed up, type parameters and inclusion paths makes no more sense in the current moshell's state

remove inclusion path and type arguments from command calls

---

cli/Cargo.toml
cli/src/repl.rs
lexer/src/delimiter.rs
lexer/src/lexer.rs
lexer/src/lib.rs
lexer/tests/sample.rs
parser/src/aspects/call.rs
parser/src/aspects/expr_list.rs
parser/src/aspects/function_declaration.rs
parser/src/aspects/group.rs
parser/src/aspects/literal.rs
parser/src/aspects/loop.rs
parser/src/aspects/match.rs
parser/src/aspects/substitution.rs
parser/src/aspects/test.rs
parser/src/aspects/type.rs
parser/src/aspects/var_declaration.rs
parser/src/aspects/var_reference.rs
parser/src/cursor.rs
parser/src/err.rs
parser/src/moves.rs
parser/src/parser.rs
parser/tests/err.rs

*Mismatched delimiters* is probably the most complicated error case to recover from. Making pairs during parsing is not quite robust, as it  give the responsibility to transform an unexpected token into a mismatched one when an error is found, a note that may be forgotten.
To leverage the parser and reduce the number of errors created in some cases (like `{(}`), delimiter pairs are verified as the lexer produces the tokens. The REPL can now use only the lexer to properly detect unterminated input. This removes the `stack_ended` boolean from the `ParseResult` struct. Erroneous input is still passed to the parser, as the infrastructure is here. It will silently discard parser errors in sections that are already marked as invalid.

Handle unmatched delimiters at lexer level

---

analyzer/src/steps/collect.rs
analyzer/src/steps/typing.rs
ast/src/lib.rs
ast/src/operation.rs
ast/src/test.rs
lexer/src/token.rs
parser/src/aspects/binary_operation.rs
parser/src/aspects/call.rs
parser/src/aspects/group.rs
parser/src/aspects/if_else.rs
parser/src/aspects/loop.rs
parser/src/aspects/match.rs
parser/src/aspects/range.rs
parser/src/aspects/redirection.rs
parser/src/aspects/test.rs
parser/src/aspects/type.rs
parser/src/moves.rs
parser/src/parser.rs
parser/tests/err.rs
parser/tests/expr.rs

In the current (mostly) recursive descent parser, operator precedence is a combination of wrappers around a left-hand side parser. It becomes more and more hazardous as additions are made. The goal here is to consolidate that by handling prefix, postfix and infix operators in the same place, with a Pratt parser.
Precedence
-----------------
The not operator (`!`) is just one prefix operator, the newly added negate operator (`-`) is another. It increased the need of a proper precedence table:
*From strong to weak, left-associative, unless noted.*
|Operator/Expression|Note|
|------------------------------|------|
|Paths|Currently handled separately|
|Method calls||
|Function calls, array indexing|Indexing is tracked by #50|
|Unary `!`, `-`||
|`as`||
|`*`, `/`, `%`||
|`+`, `-`||
|`==`, `!=`, …

Rework operator parsing

---

ast/src/function.rs
ast/src/type.rs
parser/src/aspects/assign.rs
parser/src/aspects/call.rs
parser/src/aspects/expr_list.rs
parser/src/aspects/function_declaration.rs
parser/src/aspects/type.rs
parser/src/parser.rs
parser/tests/err.rs

This PR adds a new ast structure for generic types declarations (used in function declaration's type parameters).
Also did some fixes with `Parser::parse_explicit_list` that could report a missing expected expression but still try to parse it afterward.

Parse generic type declarations

---

cli/src/cli.rs
cli/src/main.rs
cli/src/pipeline.rs
cli/src/repl.rs
cli/src/report.rs
cli/src/std.rs
compiler/src/emit/invoke.rs
vm/binding/lib.rs

The REPL would previously forget all previous prompt sources.
Tested with `MIRIFLAGS="-Zmiri-disable-isolation" cargo +nightly miri run`.

Fix shifted sources ids

---

ast/src/match.rs
lexer/src/delimiter.rs
lexer/src/lexer.rs
lexer/src/lib.rs
lexer/src/literal.rs
lexer/src/token.rs
lexer/tests/sample.rs
parser/src/aspects/if_else.rs
parser/src/aspects/literal.rs
parser/src/aspects/match.rs
parser/src/parser.rs
parser/tests/err.rs
parser/tests/with_lexer.rs

Unescape escaped characters, and fixes mismatched delimiters for the CLI by using a special lexer state for strings.
Sample test:
```kt
val msg = 'a\r\nb\')'
echo $msg
```

Delimit strings in lexer and unescape

---

analyzer/src/steps/typing/coercion.rs
analyzer/src/steps/typing/view.rs
analyzer/src/types.rs
analyzer/src/types/builtin.rs
analyzer/src/types/ty.rs
cli/lang_tests/flow/option_parse.msh
compiler/src/emit/native.rs
lib/std.msh
lib/std/convert.msh
vm/src/memory/gc.cpp
vm/src/stdlib_natives.cpp

Add a nullable reference type.
The null pointer is checked at runtime when unwrapping. This `Option` type is used when parsing integers or accessing an environment variable via the API.
This can be extended in the future with pattern matching.

Introduce an optional type

---

.dockerignore
.github/workflows/nightly.yml
.gitignore
Dockerfile
README.md
cli/Cargo.toml
cli/Makefile
cli/lang_tests/run.rs
cli/src/cli.rs
cli/src/main.rs
cli/src/std.rs

Use the [`cargo-deb`](https://github.com/kornelski/cargo-deb) helper, and expose a bash completion generator using `clap_generate`. It is versioned with the Git commit SHA.
This installs the standard library to `/usr/share/moshell/lib`, which is the last checked directory. User files are still preferred.

Create a Debian package

---

README.md
analyzer/src/steps/collect.rs
analyzer/src/steps/typing.rs
analyzer/src/steps/typing/assign.rs
analyzer/src/steps/typing/function.rs
analyzer/src/steps/typing/view.rs
analyzer/src/types/builtin.rs
ast/src/lib.rs
ast/src/range.rs
cli/lang_tests/flow/str_bytes.msh
cli/lang_tests/flow/str_split.msh
compiler/src/emit/native.rs
lexer/src/token.rs
parser/src/aspects/call.rs
parser/src/aspects/range.rs
parser/src/cursor.rs
parser/src/parser.rs
parser/tests/with_lexer.rs
vm/src/stdlib_natives.cpp

Replace `Vec[T].get(Int)` by a subscript operator, and add a way to assign to a vector via a subscript.
Subscripts are parsed like function calls, i.e. as suffix operators. They may happen before an equal sign, which create a special assignation that is not directly bound to a variable. The analyzer has been updated accordingly to treat those assignations as special method calls.
The typing phase tries to create useful diagnostics by indicating if the type is first subscriptable, and can display which types are valid indices.
Lastly, the parser no longer tries to treat function calls in a shell context. This is the opportunity to use operators from the programming context on it.
- Fixes #50 (The unpack operator will be implemented elsewhere)

Parse and analyze subscripts

---

analyzer/src/environment/symbols.rs
lexer/src/lexer.rs
lexer/src/literal.rs
lexer/src/token.rs
parser/src/aspects/call.rs
parser/src/aspects/function_declaration.rs
parser/src/aspects/literal.rs
parser/src/aspects/modules.rs
parser/src/aspects/redirection.rs
parser/src/aspects/type.rs
parser/src/parser.rs
parser/tests/err.rs
parser/tests/with_lexer.rs

The "magic" `shell` keyword created a strange parse context. Backticks are now used to delimit only the shell part.
The path parser has been simplified to include its last item. If a path only contain `reef`, the error is now caught later by the analyzer. Some hints have been added to help the user, such as indicate that paths are delimited by `::` instead of `:`.

Create shell strings and tweak common error messages

---

analyzer/src/relations.rs
analyzer/src/steps/typing.rs
analyzer/src/steps/typing/assign.rs
analyzer/src/steps/typing/bounds.rs
analyzer/src/steps/typing/exploration.rs
analyzer/src/steps/typing/function.rs
analyzer/src/steps/typing/lower.rs
analyzer/src/types.rs
analyzer/src/types/builtin.rs
analyzer/src/types/engine.rs
analyzer/src/types/hir.rs
analyzer/src/types/ty.rs
cli/lang_tests/redir/mutate_before_process.msh
compiler/src/emit.rs
compiler/src/emit/invoke.rs
compiler/src/emit/native.rs
compiler/src/lib.rs
vm/src/stdlib_natives.cpp

This PR fixes previous hazardous behavior when applying type bounds to methods with parameters typed with type's generics.
This allowed the `Vec::pop` method to return an Option[A]

Fix bounds handling for methods + Vec::pop patch

---

Cargo.lock
cli/Cargo.toml
cli/src/complete.rs
cli/src/lib.rs
cli/src/main.rs
cli/src/repl.rs
cli/src/std.rs

With the help of *reedline*, make the REPL more usable by having arrow keys, reverse search and completion for file names.
If the standard input is a terminal, switch to a dedicated *reedline* editor. It not, the code is simply read from stdin, so it can be used in external scripts. The command history is saved in the user files.
Command completion has been implemented by combining the parser output for the context handling, and the lexer output to put the completion cursor at the right spot.

Make the REPL interactive

---

.github/workflows/nightly.yml
.github/workflows/rust.yml
setup.sh
vm/src/byte_reader.cpp
vm/src/byte_reader.h
vm/src/conversions.h
vm/src/definitions/loader.cpp
vm/src/definitions/loader.h
vm/src/interpreter.cpp
vm/src/memory/call_stack.cpp
vm/src/memory/call_stack.h
vm/src/vm.cpp

The nightly setup script now checks the operating system and the architecture. Binaries are now built for the Darwin target. It fixes the macro conflict reported in #166.
The binary for macOS is crafted with the system Apple Clang compiler, that doesn't support C++ 20 concepts, so they are removed before the build. It may be better to create a C macro that checks for the compiler.

Add macOS support

---

analyzer/src/steps/collect.rs
analyzer/src/steps/typing.rs
analyzer/src/steps/typing/lower.rs
ast/src/lib.rs
ast/src/variable.rs
cli/lang_tests/flow/change_dir.msh
lexer/src/lexer.rs
lexer/src/literal.rs
lexer/src/token.rs
lib/std.msh
parser/src/aspects/literal.rs
parser/src/parser.rs
parser/tests/expr.rs
parser/tests/with_lexer.rs
vm/src/stdlib_natives.cpp
vm/tests/flow.rs

This adds the shell procedure `cd` to change the current working directory. It also allows the user to obtain their home directory and the directories of other users.
`cd` is implemented as a regular command, converted during the analysis phase into a function call. This special treatment is required in the collector and the resolver, and may be dropped in the future if the language adds proper user-defined functions/procedures that can be called without parentheses.
Tilde expansions are also handy shortcuts to certain functions. They must be at the beginning of an unquoted argument. In order to implement the parser for them properly, the `argument` parser has been completely rewritten to have fewer edge cases and repetitions *(the parser benchmark shows a ~5% time reduction)*.

Implement directory related primitives

---

cli/lang_tests/flow/preserve_pointer_info.msh
vm/src/interpreter.cpp
vm/src/memory/operand_stack.cpp
vm/src/memory/operand_stack.h
vm/src/stdlib_natives.cpp

The garbage collector identify pointers by checking if a value in the operand stack is marked in a parallel array. Because there may only one reference, it is very important to preserve the information if it is a pointer or not.
Native operations popped directly from the stack. If they were allocating new things, the GC could be executed without any indication that the reference is in fact on the native C stack. The operand stack is now wrapped in those cases, to just peek the information and to delay the pop later.
Some instructions like the swap operation treated pointers as simple integers, they weren't updating the reference positions.
Those cases are now fixed.

Preserve pointer information during native operations

---

analyzer/src/steps/collect.rs
analyzer/src/steps/typing.rs
analyzer/src/steps/typing/structure.rs
ast/src/lib.rs
ast/src/use.rs
ast/src/variable.rs
parser/src/aspects.rs
parser/src/aspects/call.rs
parser/src/aspects/expr_list.rs
parser/src/aspects/group.rs
parser/src/aspects/loop.rs
parser/src/aspects/modules.rs
parser/src/aspects/type.rs
parser/src/parser.rs
parser/tests/integration/expr.rs
parser/tests/integration/with_lexer.rs
vm/tests/integration/objects.rs

Paths may only create programmatic calls, let's change that. Disambiguate the subscript syntax to not conflict with type parameters.
It may be used to import variables from other files:
```kt
val TAU = reef::math::PI
```
When ambiguous, type parameters must use the [turbo fish](https://turbo.fish) syntax:
```kt
foo().bar[0]() // Indexes with `0` and calls the result
foo().bar::[T]() // Call the `bar` method with the `T` type
```
To do that, the parser is less greedy and adapt the expression as it advance. For instance, a method call is now parsed as a field access first.
- Fixes #167

Accept paths in expressions

---

analyzer/src/steps/collect.rs
analyzer/src/steps/typing.rs
analyzer/src/steps/typing/iterable.rs
analyzer/src/types.rs
analyzer/src/types/hir.rs
analyzer/tests/collect_debug.rs
compiler/src/emit.rs
compiler/src/emit/iterable.rs
compiler/src/emit/jump.rs
compiler/src/emit/native.rs
compiler/src/externals.rs
compiler/src/locals.rs
lib/std.msh
vm/binding/value.rs
vm/src/memory/operand_stack.cpp
vm/src/stdlib_natives.cpp
vm/tests/integration/flow.rs
vm/tests/integration/runner.rs

Adds a simpler way to iterate over vectors, integer ranges and strings.
All those iteration types are hard-coded with internal int indexes. Indexes over a vector are always incremented by one, whereas indexes in strings use the length in bytes of the current char to account for multi bytes characters.
Strings are byte-indexed, and may not be indexed in the middle of a multibyte character.
Int ranges are describes as structures in the standard library, with a variant for inclusive ranges.

Implement for in iterables

---

analyzer/src/steps/typing.rs
analyzer/src/types/hir.rs
ast/src/substitution.rs
cli/lang_tests/redir/process_substitution.msh
compiler/src/emit.rs
compiler/src/emit/invoke.rs
parser/src/aspects/call.rs
parser/src/aspects/redirection.rs
vm/src/stdlib_natives.cpp

Implement Bash-like [process substitutions](https://en.wikipedia.org/wiki/Process_substitution). Tested on GNU/Linux and macOS.
It allows using the output or the input of a process as a file. The most notorious example is the diff command, which takes two files: `diff <(echo before) <(echo after)`.
Bytecode wise, one end of the pipe must be kept opened in the parent process while the process substitution consumer is created. In the `diff` example, the pipes for the two `echo`s is kept before the `diff` process is actually created. File closing is delayed using compiler generated locals.

Add process substitutions
